
#include <ctype.h>
#include <stdint.h>
#include <stdlib.h>

#include "defs.h"
#include "dispatch-system.h"

lval set_function_pointer(int index) {
}

struct initial_symbol initial_symbols[] =
  // 'Special' base objects.
  {
    {"NIL"},
    {"T"},
    // Lambda list keywords
    {"&REST"},
    {"&BODY"},
    {"&OPTIONAL"},
    {"&KEY"},
    {"&WHOLE"},
    {"&ENVIRONMENT"},
    {"&AUX"},
    {"&ALLOW-OTHER-KEYS"},
    // functions macros, special forms
    {"DECLARE", DECLARE, -1},
    {"SPECIAL"},
    {"QUOTE", QUOTE, 1},
    {"LET", LET, -2},
    {"LET*", LET_STAR, -2},
    {"FLET", FLET, -2},
    {"LABELS", LABELS, -2},
    {"MACROLET", MACROLET, -2},
    {"SYMBOL-MACROLET", SYMBOL_MACROLET, -2},
    {"SETQ", SETQ, 2},
    {"FUNCTION", FUNCTION, 1},
    {"TAGBODY", TAGBODY, -1},
    {"GO", GO, 1},
    {"BLOCK", BLOCK, -2},
    {"RETURN-FROM", RETURN_FROM, 2},
    {"CATCH", CATCH, -2},
    {"THROW", THROW, -2},
    {"UNWIND-PROTECT", UNWIND_PROTECT, -2},
    {"IF", IF, -3},
    {"MULTIPLE-VALUE-CALL", MULTIPLE_VALUE_CALL, -2},
    {"MULTIPLE-VALUE-PROG1", MULTIPLE_VALUE_PROG1, -2},
    {"PROGN", PROGN, -1},
    {"PROGV", PROGV, -3},
    {"_SETF", SETF, 2},
    {"FINISH-FILE-STREAM", FINISH_FILE_STREAM, 1},
    {"MAKEI", MAKEI, -3},
    {"DPB", DPB, 3},
    {"LDB", LDB, 2},
    {"BACKQUOTE"},
    {"UNQUOTE"},
    {"UNQUOTE-SPLICING"},
    {"IBOUNDP", IBOUNDP, 2},
    {"LISTEN-FILE-STREAM", LISTEN_FILE_STREAM, 1},
    {"LIST", LIST, -1},
    {"VALUES", VALUES, -1},
    {"FUNCALL", FUNCALL, -2},
    {"APPLY", APPLY, -2},
    {"EQ", EQ, 2},
    {"CONS", CONS, 2},
    {"CAR", CAR, 1, SETFCAR, 2},
    {"CDR", CDR, 1, SETFCDR, 2},
    {"=", SIGN_EQUALS, -2},
    {"<", SIGN_LESS_THAN, -2},
    {"+", SIGN_PLUS, -1},
    {"-", SIGN_MINUS, -2},
    {"*", SIGN_MULTIPLICATION, -1},
    {"/", SIGN_DIVISION, -2},
    {"MAKE-FILE-STREAM", MAKE_FILE_STREAM, 2},
    {"HASH", HASH, 1},
    {"IERROR"},
    {"GENSYM", GENSYM, 0},
    {"STRING", STRING, -1},
    {"FASL", FASL, 1},
    {"MAKEJ", MAKEJ, 2},
    {"MAKEF", MAKEF, 0},
    {"FREF", FREF, 1},
    {"PRINT", PRINT, 1},
    {"GC", GC, 0},
    {"CLOSE-FILE-STREAM", CLOSE_FILE_STREAM, 1},
    {"IVAL", IVAL, 1},
    {"FLOOR", FLOOR, -2},
    {"READ-FILE-STREAM", READ_FILE_STREAM, 3},
    {"WRITE-FILE-STREAM", WRITE_FILE_STREAM, 4},
    {"LOAD", LOAD, 1},
    {"IREF", IREF, 2, SETFIREF, 3},
    {"LAMBDA"},
    {"CODE-CHAR", CODE_CHAR, 1},
    {"CHAR-CODE", CHAR_CODE, 1},
    {"*STANDARD-INPUT*"},
    {"*STANDARD-OUTPUT*"},
    {"*ERROR-OUTPUT*"},
    {"*PACKAGES*"},
    {"STRING=", STRING_EQUALS, 2},
    {"IMAKUNBOUND", IMAKUNBOUND, 2},
    {"EVAL", EVAL, -2},
    {"JREF", JREF, 2, SETFJREF, 3},
    {"RUN-PROGRAM", RUN_PROGRAM, -2},
    {"UNAME", UNAME, 0}
  };

//typedef lval(*initial_dispatchable)(lval* g, lval n,...);

void* initial_dispatchables[]  =
  {
    NULL,  // equivelent to PLACEHOLDER_DONT_USE
    eval_declare,
    NULL,
    eval_quote,
    eval_let,
    eval_letm,
    eval_flet,
    eval_labels,
    eval_macrolet,
    eval_symbol_macrolet,
    eval_setq,
    eval_function,
    eval_tagbody,
    eval_go,
    eval_block,
    eval_return_from,
    eval_catch,
    eval_throw,
    eval_unwind_protect,
    eval_if,
    eval_multiple_value_call,
    eval_multiple_value_prog1,
    eval_body,
    eval_progv,
    eval_setf,
    lfinish_fs,
    lmakei,
    ldpb,
    lldb,
    NULL,
    NULL,
    NULL,
    liboundp,
    llisten_fs,
    llist,
    lvalues,
    lfuncall,
    lapply,
    leq,
    lcons,
    lcar,
    lcdr,
    lequ,
    lless,
    lplus,
    lminus,
    ltimes,
    ldivi,
    lmake_fs,
    lhash,
    NULL,
    NULL,
    lstring,
    lfasl,
    lmakej,
    lmakef,
    lfref,
    lprint,
    gc,
    lclose_fs,
    lival,
    lfloor,
    lread_fs,
    lwrite_fs,
    lload,
    liref,
    NULL,
    NULL,
    lchar_code,
    NULL,
    NULL,
    NULL,
    NULL,
    lstring_equal,
    limakunbound,
    leval,
    ljref,
    lrp,
    luname,
    setfcar,
    setfcdr,
    setfiref,
    setfjref
};

// Looks a bit odd, but the meaning is straight forward:
// get_initial_symbols returns a pointer to a function which takes no
// arguments and has a return value of lval.
lval (*get_initial_dispatchable(enum initial_dispatchable_enum index))(lval* g, lval n,...) {
  return (lval(*) (lval * g, int n,...)) initial_dispatchables[index];
}
